# config.py (Launcher에 의해 자동 생성됨)

ASIO_DEVICE_ID = 18
SAMPLE_RATE = 44100
BLOCK_SIZE = 64

RECORD_DURATION = 20
SOFTWARE_GAIN = 60.0

METRONOME_BPM = 80
COUNTIN_BARS = 2
BEATS_PER_BAR = 4

CHROMATIC_ENABLED = True
CHROMATIC_BEATS = 4

TOLERANCE = 0.06

THRESHOLD = 0.25
SILENCE_THRESHOLD = 0.15
